//! Versioned BL-14.5 adapter from bounded conjunction synthesis to the exact
//! SEARCH→FREEZE→HOLDOUT semantic boundary.
//!
//! The synthesis kernel lives in `booleanlab-core`; the experiment-owned exact
//! truth-table identity lives in `booleanlab-discovery`. This adapter connects
//! the two without copying the conjunction evaluator or weakening the freeze
//! contract. It does not inspect task quality, resource objectives, or HOLDOUT
//! evidence.

use std::fmt;

use booleanlab_core::sparsity_synthesis::{ConjunctiveSparsityRule, RuleSynthesisError};

use crate::sparsity_semantic_freeze::{ExactSparsityRuleBinding, ResolvedPredicateParameter};
use crate::{BooleanFunction, FunctionError};

/// Version of the generic conjunction-to-freeze adapter contract.
pub const SYNTHESIS_FREEZE_ADAPTER_VERSION: &str = "bl14.conjunctive-freeze.v1";

/// Fail-closed errors while materialising exact semantics for a synthesized rule.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SynthesisFreezeAdapterError {
    Evaluation(RuleSynthesisError),
    Function(FunctionError),
}

/// Materialise a synthesized conjunction as one exact rule binding.
///
/// The complete truth table is generated by evaluating the original
/// [`ConjunctiveSparsityRule`] on every packed predicate row in canonical order.
/// Predicate schema and resolved parameters remain explicit caller-owned
/// experiment metadata and are subsequently validated by
/// `FrozenSparsityRuleSelection`.
///
/// This adapter performs no candidate selection and reads no HOLDOUT objective.
/// Its only purpose is to turn a SEARCH-produced core rule into the exact
/// semantic identity required by the existing freeze boundary.
///
/// # Errors
///
/// Propagates rule-evaluation errors and exact Boolean-function construction
/// errors. In particular, a zero-predicate conjunction cannot be represented by
/// the current scalar `BooleanFunction`, which intentionally requires at least
/// one input bit.
pub fn binding_from_conjunctive_rule(
    candidate_id: impl Into<String>,
    rule: &ConjunctiveSparsityRule,
    predicate_schema: impl Into<String>,
    resolved_parameters: Vec<ResolvedPredicateParameter>,
) -> Result<ExactSparsityRuleBinding, SynthesisFreezeAdapterError> {
    let input_bits = u32::try_from(rule.predicate_count()).map_err(|_| {
        SynthesisFreezeAdapterError::Function(FunctionError::InputWidthTooLarge {
            width: u32::MAX,
            maximum: scirust_modalg::boolean::MAX_EXACT_BITS,
        })
    })?;
    let row_count = 1usize
        .checked_shl(input_bits)
        .ok_or(SynthesisFreezeAdapterError::Function(
            FunctionError::InputWidthTooLarge {
                width: input_bits,
                maximum: scirust_modalg::boolean::MAX_EXACT_BITS,
            },
        ))?;

    let mut predicates = vec![false; rule.predicate_count()];
    let mut truth_table = Vec::with_capacity(row_count);
    for row in 0..row_count {
        for (bit, predicate) in predicates.iter_mut().enumerate() {
            *predicate = ((row >> bit) & 1) != 0;
        }
        let active = rule
            .evaluate(&predicates)
            .map_err(SynthesisFreezeAdapterError::Evaluation)?;
        truth_table.push(u8::from(active));
    }

    let function = BooleanFunction::new(input_bits, truth_table)
        .map_err(SynthesisFreezeAdapterError::Function)?;
    Ok(ExactSparsityRuleBinding {
        candidate_id: candidate_id.into(),
        function,
        predicate_schema: predicate_schema.into(),
        resolved_parameters,
    })
}

impl fmt::Display for SynthesisFreezeAdapterError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{self:?}")
    }
}

impl std::error::Error for SynthesisFreezeAdapterError {}

#[cfg(test)]
mod tests {
    use super::*;
    use booleanlab_core::sparsity_synthesis::{SynthesisRow, synthesize_exact_conjunction};

    use crate::sparsity_freeze::FrozenSparsitySelection;
    use crate::sparsity_rule_search::{SparsityEvaluationPhase, SparsityRuleCandidate};
    use crate::sparsity_semantic_freeze::{
        FrozenSparsityRuleSelection, SparsitySemanticFreezeError,
    };

    fn exhaustive_two_input_rows(label: fn(bool, bool) -> bool) -> Vec<SynthesisRow> {
        [false, true]
            .into_iter()
            .flat_map(|left| {
                [false, true]
                    .into_iter()
                    .map(move |right| SynthesisRow::new(vec![left, right], label(left, right)))
            })
            .collect()
    }

    fn candidate(candidate_id: &str, phase: SparsityEvaluationPhase) -> SparsityRuleCandidate {
        SparsityRuleCandidate {
            candidate_id: candidate_id.to_owned(),
            phase,
            quality_loss_units: 0,
            retained_units: 50,
            total_units: 100,
            controller_cost_units: 2,
            effective_compute_units: 500,
            memory_traffic_bytes: 3_200,
            latency_ns: 5_000,
            rule_complexity_units: 2,
        }
    }

    fn binding_for(candidate_id: &str, rule: &ConjunctiveSparsityRule) -> ExactSparsityRuleBinding {
        binding_from_conjunctive_rule(candidate_id, rule, "v1:[left,right]", Vec::new()).unwrap()
    }

    #[test]
    fn materialises_canonical_truth_table_from_core_rule() {
        let rows = exhaustive_two_input_rows(|left, right| left && right);
        let rule = synthesize_exact_conjunction(&rows, 2).unwrap().unwrap();
        let binding = binding_for("and", &rule);

        assert_eq!(
            SYNTHESIS_FREEZE_ADAPTER_VERSION,
            "bl14.conjunctive-freeze.v1"
        );
        assert_eq!(binding.function.input_bits(), 2);
        assert_eq!(binding.function.truth_table(), &[0, 0, 0, 1]);
    }

    #[test]
    fn synthesized_rule_roundtrips_through_search_freeze_and_holdout_validation() {
        let rows = exhaustive_two_input_rows(|left, right| left && right);
        let rule = synthesize_exact_conjunction(&rows, 2).unwrap().unwrap();
        let search = [candidate("rule-a", SparsityEvaluationPhase::Search)];
        let selection = FrozenSparsitySelection::from_search_frontier(&search).unwrap();
        let frozen = FrozenSparsityRuleSelection::bind_search_rules(
            selection,
            &[binding_for("rule-a", &rule)],
        )
        .unwrap();
        let holdout = [candidate("rule-a", SparsityEvaluationPhase::Holdout)];

        assert_eq!(
            frozen.validate_holdout(&holdout, &[binding_for("rule-a", &rule)]),
            Ok(())
        );
    }

    #[test]
    fn changed_synthesized_rule_is_detected_as_semantic_drift() {
        let and_rows = exhaustive_two_input_rows(|left, right| left && right);
        let left_rows = exhaustive_two_input_rows(|left, _| left);
        let and_rule = synthesize_exact_conjunction(&and_rows, 2).unwrap().unwrap();
        let left_rule = synthesize_exact_conjunction(&left_rows, 2)
            .unwrap()
            .unwrap();
        let search = [candidate("rule-a", SparsityEvaluationPhase::Search)];
        let selection = FrozenSparsitySelection::from_search_frontier(&search).unwrap();
        let frozen = FrozenSparsityRuleSelection::bind_search_rules(
            selection,
            &[binding_for("rule-a", &and_rule)],
        )
        .unwrap();
        let holdout = [candidate("rule-a", SparsityEvaluationPhase::Holdout)];

        assert_eq!(
            frozen.validate_holdout(&holdout, &[binding_for("rule-a", &left_rule)]),
            Err(SparsitySemanticFreezeError::RuleSemanticMismatch {
                candidate_id: "rule-a".to_owned(),
            })
        );
    }

    #[test]
    fn zero_predicate_rule_fails_closed_at_exact_function_boundary() {
        let rows = [SynthesisRow::new(Vec::new(), true)];
        let rule = synthesize_exact_conjunction(&rows, 0).unwrap().unwrap();
        assert_eq!(
            binding_from_conjunctive_rule("constant", &rule, "v1:[]", Vec::new()),
            Err(SynthesisFreezeAdapterError::Function(
                FunctionError::ZeroInputs,
            ))
        );
    }
}
