//! Exact three-valued Strong-Kleene reference semantics.
//!
//! This module is an experimental/differential oracle for `BooleanLab`. It is
//! intentionally independent from any production runtime so downstream
//! projects can compare their own implementations against small, exhaustive
//! truth tables without linking `BooleanLab` into an actuation path.

/// One value in Strong-Kleene three-valued logic.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum KleeneValue {
    False,
    Unknown,
    True,
}

impl KleeneValue {
    /// Logical negation.
    #[must_use]
    pub const fn not(self) -> Self {
        match self {
            Self::False => Self::True,
            Self::Unknown => Self::Unknown,
            Self::True => Self::False,
        }
    }

    /// Strong-Kleene conjunction.
    #[must_use]
    pub const fn and(self, rhs: Self) -> Self {
        match (self, rhs) {
            (Self::False, _) | (_, Self::False) => Self::False,
            (Self::True, Self::True) => Self::True,
            _ => Self::Unknown,
        }
    }

    /// Strong-Kleene disjunction.
    #[must_use]
    pub const fn or(self, rhs: Self) -> Self {
        match (self, rhs) {
            (Self::True, _) | (_, Self::True) => Self::True,
            (Self::False, Self::False) => Self::False,
            _ => Self::Unknown,
        }
    }

    /// Three-valued exclusive-or.
    #[must_use]
    pub const fn xor(self, rhs: Self) -> Self {
        match (self, rhs) {
            (Self::Unknown, _) | (_, Self::Unknown) => Self::Unknown,
            (Self::True, Self::False) | (Self::False, Self::True) => Self::True,
            _ => Self::False,
        }
    }

    /// Material implication under Strong-Kleene semantics: `NOT(a) OR b`.
    #[must_use]
    pub const fn implies(self, rhs: Self) -> Self {
        self.not().or(rhs)
    }
}

/// Every truth value in canonical order.
pub const KLEENE_VALUES: [KleeneValue; 3] =
    [KleeneValue::False, KleeneValue::Unknown, KleeneValue::True];

/// One exhaustive binary truth-table row.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BinaryTruthRow {
    pub lhs: KleeneValue,
    pub rhs: KleeneValue,
    pub and: KleeneValue,
    pub or: KleeneValue,
    pub xor: KleeneValue,
    pub implies: KleeneValue,
}

/// Frozen complete 3 x 3 Strong-Kleene binary oracle.
///
/// The expected values are written explicitly rather than generated by the
/// operators under test. This keeps the small-domain reference useful as an
/// independent differential fixture.
pub const KLEENE_BINARY_TRUTH_TABLE: [BinaryTruthRow; 9] = [
    BinaryTruthRow {
        lhs: KleeneValue::False,
        rhs: KleeneValue::False,
        and: KleeneValue::False,
        or: KleeneValue::False,
        xor: KleeneValue::False,
        implies: KleeneValue::True,
    },
    BinaryTruthRow {
        lhs: KleeneValue::False,
        rhs: KleeneValue::Unknown,
        and: KleeneValue::False,
        or: KleeneValue::Unknown,
        xor: KleeneValue::Unknown,
        implies: KleeneValue::True,
    },
    BinaryTruthRow {
        lhs: KleeneValue::False,
        rhs: KleeneValue::True,
        and: KleeneValue::False,
        or: KleeneValue::True,
        xor: KleeneValue::True,
        implies: KleeneValue::True,
    },
    BinaryTruthRow {
        lhs: KleeneValue::Unknown,
        rhs: KleeneValue::False,
        and: KleeneValue::False,
        or: KleeneValue::Unknown,
        xor: KleeneValue::Unknown,
        implies: KleeneValue::Unknown,
    },
    BinaryTruthRow {
        lhs: KleeneValue::Unknown,
        rhs: KleeneValue::Unknown,
        and: KleeneValue::Unknown,
        or: KleeneValue::Unknown,
        xor: KleeneValue::Unknown,
        implies: KleeneValue::Unknown,
    },
    BinaryTruthRow {
        lhs: KleeneValue::Unknown,
        rhs: KleeneValue::True,
        and: KleeneValue::Unknown,
        or: KleeneValue::True,
        xor: KleeneValue::Unknown,
        implies: KleeneValue::True,
    },
    BinaryTruthRow {
        lhs: KleeneValue::True,
        rhs: KleeneValue::False,
        and: KleeneValue::False,
        or: KleeneValue::True,
        xor: KleeneValue::True,
        implies: KleeneValue::False,
    },
    BinaryTruthRow {
        lhs: KleeneValue::True,
        rhs: KleeneValue::Unknown,
        and: KleeneValue::Unknown,
        or: KleeneValue::True,
        xor: KleeneValue::Unknown,
        implies: KleeneValue::Unknown,
    },
    BinaryTruthRow {
        lhs: KleeneValue::True,
        rhs: KleeneValue::True,
        and: KleeneValue::True,
        or: KleeneValue::True,
        xor: KleeneValue::False,
        implies: KleeneValue::True,
    },
];

/// Return the frozen exhaustive binary oracle by value for simple fixture use.
#[must_use]
pub const fn exhaustive_binary_truth_table() -> [BinaryTruthRow; 9] {
    KLEENE_BINARY_TRUTH_TABLE
}

/// One instruction in a postfix Strong-Kleene expression program.
///
/// Postfix form keeps the differential oracle small and deterministic while
/// allowing downstream projects to serialize their own rule trees into a
/// neutral sequence before comparison.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum KleeneInstruction {
    Input(usize),
    Constant(KleeneValue),
    Not,
    And,
    Or,
    Xor,
    Implies,
}

/// Structural failure while evaluating a Strong-Kleene postfix program.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum KleeneEvalError {
    InputOutOfRange {
        instruction: usize,
        input: usize,
        input_len: usize,
    },
    StackUnderflow {
        instruction: usize,
        needed: usize,
        available: usize,
    },
    InvalidFinalStackDepth {
        depth: usize,
    },
}

/// Evaluate a postfix expression exactly under the frozen Strong-Kleene rules.
///
/// Binary operators pop the right-hand side first and the left-hand side
/// second, preserving implication direction. Malformed programs fail closed
/// instead of manufacturing a Boolean default for missing evidence.
pub fn evaluate_kleene_program(
    program: &[KleeneInstruction],
    inputs: &[KleeneValue],
) -> Result<KleeneValue, KleeneEvalError> {
    let mut stack = Vec::with_capacity(program.len());

    for (instruction, op) in program.iter().copied().enumerate() {
        match op {
            KleeneInstruction::Input(input) => {
                let value = inputs
                    .get(input)
                    .copied()
                    .ok_or(KleeneEvalError::InputOutOfRange {
                        instruction,
                        input,
                        input_len: inputs.len(),
                    })?;
                stack.push(value);
            }
            KleeneInstruction::Constant(value) => stack.push(value),
            KleeneInstruction::Not => {
                let available = stack.len();
                let value = stack.pop().ok_or(KleeneEvalError::StackUnderflow {
                    instruction,
                    needed: 1,
                    available,
                })?;
                stack.push(value.not());
            }
            KleeneInstruction::And
            | KleeneInstruction::Or
            | KleeneInstruction::Xor
            | KleeneInstruction::Implies => {
                let available = stack.len();
                if available < 2 {
                    return Err(KleeneEvalError::StackUnderflow {
                        instruction,
                        needed: 2,
                        available,
                    });
                }
                let rhs = stack.pop().expect("stack depth checked");
                let lhs = stack.pop().expect("stack depth checked");
                let result = match op {
                    KleeneInstruction::And => lhs.and(rhs),
                    KleeneInstruction::Or => lhs.or(rhs),
                    KleeneInstruction::Xor => lhs.xor(rhs),
                    KleeneInstruction::Implies => lhs.implies(rhs),
                    KleeneInstruction::Input(_)
                    | KleeneInstruction::Constant(_)
                    | KleeneInstruction::Not => unreachable!("binary arm only"),
                };
                stack.push(result);
            }
        }
    }

    if stack.len() != 1 {
        return Err(KleeneEvalError::InvalidFinalStackDepth { depth: stack.len() });
    }

    Ok(stack[0])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn negation_is_exact() {
        assert_eq!(KleeneValue::False.not(), KleeneValue::True);
        assert_eq!(KleeneValue::Unknown.not(), KleeneValue::Unknown);
        assert_eq!(KleeneValue::True.not(), KleeneValue::False);
    }

    #[test]
    fn binary_table_is_exhaustive_and_unique() {
        let rows = exhaustive_binary_truth_table();
        for lhs in KLEENE_VALUES {
            for rhs in KLEENE_VALUES {
                assert_eq!(
                    rows.iter()
                        .filter(|row| row.lhs == lhs && row.rhs == rhs)
                        .count(),
                    1
                );
            }
        }
    }

    #[test]
    fn operators_match_the_frozen_oracle() {
        for row in KLEENE_BINARY_TRUTH_TABLE {
            assert_eq!(row.lhs.and(row.rhs), row.and);
            assert_eq!(row.lhs.or(row.rhs), row.or);
            assert_eq!(row.lhs.xor(row.rhs), row.xor);
            assert_eq!(row.lhs.implies(row.rhs), row.implies);
        }
    }

    #[test]
    fn unknown_is_not_false() {
        let u = KleeneValue::Unknown;
        assert_eq!(u.and(KleeneValue::True), KleeneValue::Unknown);
        assert_eq!(u.or(KleeneValue::False), KleeneValue::Unknown);
        assert_eq!(u.xor(KleeneValue::False), KleeneValue::Unknown);
        assert_eq!(u.implies(KleeneValue::False), KleeneValue::Unknown);
    }

    #[test]
    fn decisive_operands_short_circuit_truth_not_evidence() {
        let u = KleeneValue::Unknown;
        assert_eq!(KleeneValue::False.and(u), KleeneValue::False);
        assert_eq!(KleeneValue::True.or(u), KleeneValue::True);
    }

    #[test]
    fn known_inputs_reduce_to_classical_boolean_logic() {
        for lhs in [KleeneValue::False, KleeneValue::True] {
            for rhs in [KleeneValue::False, KleeneValue::True] {
                let lhs_bool = lhs == KleeneValue::True;
                let rhs_bool = rhs == KleeneValue::True;
                assert_eq!(lhs.and(rhs) == KleeneValue::True, lhs_bool && rhs_bool);
                assert_eq!(lhs.or(rhs) == KleeneValue::True, lhs_bool || rhs_bool);
                assert_eq!(lhs.xor(rhs) == KleeneValue::True, lhs_bool ^ rhs_bool);
                assert_eq!(lhs.implies(rhs) == KleeneValue::True, !lhs_bool || rhs_bool);
            }
        }
    }

    #[test]
    fn conjunction_disjunction_and_xor_are_commutative() {
        for lhs in KLEENE_VALUES {
            for rhs in KLEENE_VALUES {
                assert_eq!(lhs.and(rhs), rhs.and(lhs));
                assert_eq!(lhs.or(rhs), rhs.or(lhs));
                assert_eq!(lhs.xor(rhs), rhs.xor(lhs));
            }
        }
    }

    #[test]
    fn de_morgan_holds_exhaustively() {
        for lhs in KLEENE_VALUES {
            for rhs in KLEENE_VALUES {
                assert_eq!(lhs.and(rhs).not(), lhs.not().or(rhs.not()));
                assert_eq!(lhs.or(rhs).not(), lhs.not().and(rhs.not()));
            }
        }
    }

    #[test]
    fn postfix_program_matches_direct_semantics_exhaustively() {
        // (x0 AND NOT(x1)) OR x1
        let program = [
            KleeneInstruction::Input(0),
            KleeneInstruction::Input(1),
            KleeneInstruction::Not,
            KleeneInstruction::And,
            KleeneInstruction::Input(1),
            KleeneInstruction::Or,
        ];

        for lhs in KLEENE_VALUES {
            for rhs in KLEENE_VALUES {
                assert_eq!(
                    evaluate_kleene_program(&program, &[lhs, rhs]),
                    Ok(lhs.and(rhs.not()).or(rhs))
                );
            }
        }
    }

    #[test]
    fn implication_preserves_operand_direction() {
        let program = [
            KleeneInstruction::Input(0),
            KleeneInstruction::Input(1),
            KleeneInstruction::Implies,
        ];
        for lhs in KLEENE_VALUES {
            for rhs in KLEENE_VALUES {
                assert_eq!(
                    evaluate_kleene_program(&program, &[lhs, rhs]),
                    Ok(lhs.implies(rhs))
                );
            }
        }
    }

    #[test]
    fn malformed_programs_fail_closed() {
        assert_eq!(
            evaluate_kleene_program(&[KleeneInstruction::Input(1)], &[KleeneValue::True]),
            Err(KleeneEvalError::InputOutOfRange {
                instruction: 0,
                input: 1,
                input_len: 1,
            })
        );
        assert_eq!(
            evaluate_kleene_program(&[KleeneInstruction::And], &[]),
            Err(KleeneEvalError::StackUnderflow {
                instruction: 0,
                needed: 2,
                available: 0,
            })
        );
        assert_eq!(
            evaluate_kleene_program(
                &[
                    KleeneInstruction::Constant(KleeneValue::False),
                    KleeneInstruction::Constant(KleeneValue::True),
                ],
                &[]
            ),
            Err(KleeneEvalError::InvalidFinalStackDepth { depth: 2 })
        );
        assert_eq!(
            evaluate_kleene_program(&[], &[]),
            Err(KleeneEvalError::InvalidFinalStackDepth { depth: 0 })
        );
    }
}
